# Generated by Django 3.2.20 on 2024-01-31 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024, message='Нельзя указать год в будущем')], verbose_name='Год выпуска произведения'),
        ),
    ]
